---
title: "COVID-19"
date: "11/19/2021"
output: github_document 
---

```{r setup}
library(tidyverse)
library(lubridate)
library(broom)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

## Modeling case death
```{r}
# change the us_states_long data in weekly average
us_states <- us_states_long %>%
  # discard dates before cases were tracked.
  filter(date > as.Date("2020-03-01")) %>%
  pivot_wider(names_from = "data_type", values_from = "value") %>%
  rename(state = location) %>%
  select(date, state, cases_total, deaths_total) %>%
  mutate(state = as_factor(state)) %>%
  arrange(state, date) %>%
  group_by(state) %>%
  # smooth the data with 7 day moving average
  mutate(cases_7day = (cases_total - lag(cases_total, 7)) / 7) %>%
  mutate(deaths_7day = (deaths_total - lag(deaths_total, 7)) / 7)

# national level aggregation
us <- us_states %>%
  group_by(date) %>%
  summarize(across(
    .cols = where(is.double),
    .fns = function(x) sum(x, na.rm = T),
    .names = "{col}"
  ))

us[10:20, ] %>%
  gt() %>%
  tab_options(table.width = "80%") %>%
  opt_all_caps()
```

```{r}
# Line graphs showing trends in cases and deaths in the U.S. and NYC, respectively
coeff <- 20   # deaths_7day is too small to plot at the same time with cases so I just add a random number to make deaths_7day more visible, "10" is not work so well, ~30 seems more suitable 
us %>%
  ggplot(aes(date, cases_7day)) +
  geom_line(color = "orange") +
  theme(legend.position = "none") +
  geom_line(aes(x = date, y = deaths_7day * coeff), color = "red") +
  scale_y_continuous(
    labels = scales::comma,
    name = "Cases",
    sec.axis = sec_axis(deaths_7day ~ . / coeff,
      name = "Deaths",
      labels = scales::comma
    )
  ) +
  theme(
    axis.title.y = element_text(color = "orange", size = 13),
    axis.title.y.right = element_text(color = "red", size = 13)
  ) +
  labs(
    title = "U.S. Cases vs. Deaths",
    subtitle = "7-Day Average",
    caption = "Source: NY Times, Arthur Steinmetz",
    x = "Date"
  )
# cases rises while deaths smoothly diminish?
```

```{r}
#  linear regression lines showing case rates and death rates
lm_df = 
  lm(deaths_7day ~ cases_7day + date, data = us) %>%
  broom::tidy() 

# both have significant p-value while "date" weights more than "cases_7day" in predicting the deaths_7day. So should adjust regression for time series.
```

## assuming increase rate analysis for before and after vaccine
```{r vaccine before}
# if assuming 2% increase per day since I did not calculate
before_vac <- 0:284 
#from 2020 March 1st to 12.14 the first vaccine available in the US=9*30 + 14

  cases =
    round(104*(1.02^before_vac), digits = 0) 
#104 cases from above US aggregation data on 2020 3.2
  
  rbind(before_vac, cases)

# and the number of increasing 
  ggplot() + 
    geom_point(aes(x = before_vac, y = cases)) + 
    geom_line(aes(x = before_vac, y = cases)) + 
    xlab("Day") + 
    ylab("Total Cases")
  
# exponential increment
```

```{r after vaccine}
# if assuming 1% increase per day after vaccine (maybe can use R0 from CDC) till day 385
after_vac <- 285:385

# data for without vaccine
without_vac <- c(before_vac, after_vac)
cases_after <- round(104*(1.02^without_vac),digits = 0)

# data with vaccine
case_vac.285to300 =
    round(cases[285]*(1.01^(1:101)), digits = 0) 

# plot comparing hypothesized increase for before and after vaccine
  ggplot() + 
    geom_line(aes(x = without_vac,
                  y = cases_after)) +
    geom_point(aes(x = before_vac, 
                   y = cases)) + 
    geom_line(aes(x = after_vac, 
                  y = case_vac.285to300), col = "blue") +
    xlab("Day") + 
    ylab("Total Cases")

  #(if the increase rate under without and with vaccine is known) graph can show vaccine and bending the curve of cases increment (without interfere-black, with interfere-blue)
  #can compare this with actual cases number see if the vaccine is as effective as our model
  
```
-   Similar graphs with markers for initiation of vaccine distribution
-   Bar graphs showing differences in COVID-19 deaths by different
    subgroups (age, sex, race, etc.)
-   Line graph showing trends in mask usage, disease rates, and vaccine
    rates

