---
title: "COVID-19 Trends Pre- and Post-Vaccine Wide Availability"
output: github_document
---

```{r, message = F}
library(tidyverse)
```

The date 4/19/21 was used as the date when vaccines became available for all adults in the U.S. Plots were made with regressions forced to intersect origin point (0, 0) and not forced to. Slopes are included for both at the end of the plots. Date was converted to "day of pandemic" in order to regress on a numeric variable instead of YYYY-MM-DD.

## Cases

```{r}
us_covid = read_csv("./data/us.csv") %>% 
  mutate(day = 1:663)

total_us_case_lm = lm(cases ~ 0 + day, data = us_covid)
us_covid %>% 
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ 0 + x) +
  labs(title = "U.S. COVID-19 Cases from 1/21/20 to 11/13/21",
       x = "Date", y = "Cases")

pre_vacc_case_lm = 
  us_covid %>% 
  slice(1:454) %>% 
  lm(cases ~ 0 + day, data = .)
us_covid %>% 
  slice(1:454) %>% 
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ 0 + x) +
  labs(title = "U.S. COVID-19 Cases from 1/21/20 to 4/18/21 (Pre-Vaccine)",
       x = "Date", y = "Cases")

post_vacc_case_lm = 
  us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  lm(new_cases ~ 0 + day, data = .)
us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  ggplot(aes(x = new_day, y = new_cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ 0 + x) +
  labs(title = "U.S. COVID-19 Cases from 4/19/21 to 11/13/21 (Post-Vaccine)",
       x = "Date", y = "Cases")
```

## Deaths

```{r}
total_us_death_lm = lm(deaths ~ 0 + day, data = us_covid)
us_covid %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ 0 + x) +
  labs(title = "U.S. COVID-19 Deaths from 1/21/20 to 11/13/21",
       x = "Date", y = "Deaths")

pre_vacc_death_lm = 
  us_covid %>% 
  slice(1:454) %>% 
  lm(deaths ~ 0 + day, data = .)
us_covid %>% 
  slice(1:454) %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ 0 + x) +
  labs(title = "U.S. COVID-19 Deaths from 1/21/20 to 4/18/21 (Pre-Vaccine)",
       x = "Date", y = "Deaths")

post_vacc_death_lm = 
  us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  lm(new_deaths ~ 0 + day, data = .)
us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  ggplot(aes(x = new_day, y = new_deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ 0 + x) +
  labs(title = "U.S. COVID-19 Deaths from 4/19/21 to 11/13/21 (Post-Vaccine)",
       x = "Date", y = "Deaths")
```

## Slopes

```{r}
tibble(
  metric = "slope",
  total_case = total_us_case_lm$coefficients,
  pre_vacc_case = pre_vacc_case_lm$coefficients,
  post_vacc_case = post_vacc_case_lm$coefficients,
  total_death = total_us_death_lm$coefficients,
  pre_vacc_death = pre_vacc_death_lm$coefficients,
  post_vacc_death = post_vacc_death_lm$coefficients
  ) %>% 
  knitr::kable()

```

## Cases

```{r}
us_covid = read_csv("./data/us.csv") %>% 
  mutate(day = 1:663)

total_us_case_lm = lm(cases ~ day, data = us_covid)
us_covid %>% 
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "U.S. COVID-19 Cases from 1/21/20 to 11/13/21",
       x = "Date", y = "Cases")

pre_vacc_case_lm = 
  us_covid %>% 
  slice(1:454) %>% 
  lm(cases ~ day, data = .)
us_covid %>% 
  slice(1:454) %>% 
  ggplot(aes(x = day, y = cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "U.S. COVID-19 Cases from 1/21/20 to 4/18/21 (Pre-Vaccine)",
       x = "Date", y = "Cases")

post_vacc_case_lm = 
  us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  lm(new_cases ~ day, data = .)
us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  ggplot(aes(x = new_day, y = new_cases)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "U.S. COVID-19 Cases from 4/19/21 to 11/13/21 (Post-Vaccine)",
       x = "Date", y = "Cases")
```

## Deaths

```{r}
total_us_death_lm = lm(deaths ~ day, data = us_covid)
us_covid %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "U.S. COVID-19 Deaths from 1/21/20 to 11/13/21",
       x = "Date", y = "Deaths")

pre_vacc_death_lm = 
  us_covid %>% 
  slice(1:454) %>% 
  lm(deaths ~ day, data = .)
us_covid %>% 
  slice(1:454) %>% 
  ggplot(aes(x = day, y = deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "U.S. COVID-19 Deaths from 1/21/20 to 4/18/21 (Pre-Vaccine)",
       x = "Date", y = "Deaths")

post_vacc_death_lm = 
  us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  lm(new_deaths ~ day, data = .)
us_covid %>% 
  slice(455:663) %>% 
  mutate(new_cases = cases - 31754642,
         new_deaths = deaths - 567314,
         new_day = day - 454) %>%
  ggplot(aes(x = new_day, y = new_deaths)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x) +
  labs(title = "U.S. COVID-19 Deaths from 4/19/21 to 11/13/21 (Post-Vaccine)",
       x = "Date", y = "Deaths")
```

## Slopes

```{r}
tibble(
  metric = c("intercept", "slope"),
  total_case = total_us_case_lm$coefficients,
  pre_vacc_case = pre_vacc_case_lm$coefficients,
  post_vacc_case = post_vacc_case_lm$coefficients,
  total_death = total_us_death_lm$coefficients,
  pre_vacc_death = pre_vacc_death_lm$coefficients,
  post_vacc_death = post_vacc_death_lm$coefficients
  ) %>% 
  knitr::kable()

```
